### ISSUE TITLE
XIAO timer calls and MACRO to enable the XIAO ARM timers setup?

### ISSUE THREAD

**Issue by m-r-m-s** [sigmdel/xiao_m0_sketches#1]
Hi, I am having very little success in trying to determine if XIAO has full Arduino support or not? Your [overview](https://www.sigmdel.ca/michel/ha/xiao/seeeduino_xiao_01_en.html#timers) has been very helpful in my research but as a novice coder, I am trying to fill in the gaps. Specifically, I am wondering if you can confirm whether XIAO support `interrupts()` and `noInterrupts()` calls or not? 

So far I have found the following: [https://forum.seeedstudio.com/t/interrupts-and-nointerrupts-is-undefined/254943](https://forum.seeedstudio.com/t/interrupts-and-nointerrupts-is-undefined/254943) . 

I would like to be able to use the [uClock library](https://github.com/midilab/uClock/blob/0e7296ce58561059248dc3f8b5c1b33cdf9729b7/src/uClock.cpp#L33) mentioned in the forum post above and I have reached out to the developer. Here is what they have said: 

> Its an arm microcontroller there, so if their support to arduino is fine you should be able to access the timers interface via uClock and interrupts/noInterrupts calls.
> 
> It will only need to add a MACRO(that i don't know what it is) along with uClock code to enable the XIAO ARM timers setup... just like we have for teensyduino 
([https://github.com/midilab/uClock/issues/6#issuecomment-1110054736](https://github.com/midilab/uClock/issues/6#issuecomment-1110054736))

And do you know if this is the MACRO that is needed: 
[https://forum.seeedstudio.com/t/macro-for-distigushing-xiao-akin-to-arduino-arch-avr/262142/2](https://forum.seeedstudio.com/t/macro-for-distigushing-xiao-akin-to-arduino-arch-avr/262142/2)

Any insight would be greatly appreciated. Thanks!

**Comment by sigmdel** [comment]
1. `Interrupts()` and `noInterrupts()` are now defined.

2. `SEEED_XIAO_M0` is the correct macro to define code that will be compiled only for the Seeeduino XIAO.

3. It is hard to understand what the uClock dev is trying to say. An Arduino core is an abstraction layer which translates low-level Arduino APIs  such as `digitalRead`, `digitalWrite`, `delay`, and so on into actual code that will work with a particular micro controller. The [Arduino Language Reference](https://www.arduino.cc/reference/en/) does not define timers. The  `IntervalTimer` class which the library uses when running on a Teensy is not found in the SAMD 21 Arduino Core for the XIAO. To use uClock with the XIAO, it would be necessary to create such a class for the SAMD 21; not a trivial task.

**Comment by sigmdel** [comment]
I closing this issue which is not directly related to the repository.

**Comment by m-r-m-s** [comment]
> I closing this issue which is not directly related to the repository.

Understood. Thank you for the reply and answering all my questions. Very helpful as is all of your XIAO overview documentation and this repository.
